use super::*;
impl Eclipse {
    pub(in crate::ui) fn server_settings_window(&mut self,ctx:&egui::Context){
        if !self.server_settings{return;}
        let name=self.server.metadata["name"].as_str().unwrap_or("Server").to_owned();
        let close=crate::settings_layout::shell(ctx,"server-settings",&name,"Server Settings",|ui,size|{
            ui.horizontal_top(|ui|{
                egui::Frame::NONE.fill(RAIL).inner_margin(16).show(ui,|ui|{ui.vertical(|ui|{ui.set_width(188.);ui.set_height(size.y-32.);
                    egui::ScrollArea::vertical().id_salt("server-settings-nav").max_height(size.y-32.).show(ui,|ui|{
                        for(category,pages)in preferences::SERVER_CATEGORIES{ui.add_space(12.);ui.label(RichText::new(*category).size(10.).strong().color(MUTED));
                            for page in *pages{if crate::widgets::nav_row(ui,page,self.server_page==*page,if self.server_page==*page{TEXT}else{MUTED}).clicked(){self.server_page=(*page).into();self.load_server_page();}}
                        }
                    });
                });});
                egui::Frame::NONE.inner_margin(egui::Margin::symmetric(22,16)).show(ui,|ui|{ui.vertical(|ui|{ui.set_width(size.x-280.);
                    egui::ScrollArea::vertical().id_salt(("server-settings-body",&self.server_page)).max_height(size.y-32.).auto_shrink([false,false]).show(ui,|ui|{self.server_body(ui);});
                });});
            });
        });if close{self.server_settings=false;}
    }
    pub(in crate::ui) fn load_server_page(&mut self){
        let guild=self.server.id.clone();let page=self.server_page.clone();let key=format!("server:{guild}:{page}");
        let suffix=match page.as_str(){"Overview"|"Community"|"Boost Status"=>{self.request_feature(&format!("guild:{guild}"),format!("/guilds/{guild}?with_counts=true"));return;},"Roles"=>{self.load_roles();return;},"Members"=>{self.refresh_members();return;},"Channels"=>{self.send_command(Command::Channels(guild));return;},"Emoji"=>"emojis","Stickers"=>"stickers","Soundboard"=>"soundboard-sounds","Invites"=>"invites","Bans"=>"bans?limit=100","Audit Log"=>"audit-logs?limit=50","Integrations"=>"integrations","Webhooks"=>"webhooks","AutoMod"=>"auto-moderation/rules","Onboarding"=>"onboarding","Welcome Screen"=>"welcome-screen","Server Widget"=>"widget","Server Template"=>"templates","Vanity URL"=>"vanity-url","Notifications"=>{self.request_feature(&key,format!("/users/@me/guilds/{guild}/settings"));return;},_=>return};
        self.request_feature(&key,format!("/guilds/{guild}/{suffix}"));
    }
    fn server_body(&mut self,ui:&mut egui::Ui){
        let page=self.server_page.clone();let guild=self.server.id.clone();let actor=self.user.as_ref().map(|u|u.id.clone()).unwrap_or_default();let manage=self.server.can(&actor,5);let key=format!("server:{guild}:{page}");heading(ui,&page,crate::settings_layout::description(&page));
        crate::settings_layout::card(ui,|ui|{self.feature_status(ui,&format!("guild:{guild}"));self.feature_status(ui,&key);
        match page.as_str(){
            "Overview"|"Community"=>{
                if self.server_edit.is_object(){ui.add_enabled_ui(manage||self.preview,|ui|{
                    text(ui,&mut self.server_edit,"name","Server name",false);text(ui,&mut self.server_edit,"description","Description",true);language_picker(ui,&mut self.server_edit,"preferred_locale");
                    choice(ui,&mut self.server_edit,"verification_level","Verification level",&[(0,"None"),(1,"Low · verified email"),(2,"Medium · account age"),(3,"High · membership age"),(4,"Highest · verified phone")]);
                    choice(ui,&mut self.server_edit,"default_message_notifications","Default notifications",&[(0,"All messages"),(1,"Only mentions")]);choice(ui,&mut self.server_edit,"explicit_content_filter","Sensitive content filtering",&[(0,"Disabled"),(1,"Members without roles"),(2,"All members")]);
                    choice(ui,&mut self.server_edit,"afk_timeout","Move inactive members after",&[(60,"1 minute"),(300,"5 minutes"),(900,"15 minutes"),(1800,"30 minutes"),(3600,"1 hour")]);
                    for(field,label)in[("afk_channel_id","AFK voice channel"),("system_channel_id","System messages channel"),("rules_channel_id","Rules channel"),("public_updates_channel_id","Community updates channel"),("safety_alerts_channel_id","Safety alerts channel")]{channel_choice(ui,&mut self.server_edit,field,label,&self.channels);}
                    let mut flags=self.server_edit["system_channel_flags"].as_u64().unwrap_or(0);ui.strong("System messages");for(bit,label)in[(0,"Suppress join messages"),(1,"Suppress boost messages"),(2,"Suppress server tips"),(3,"Suppress join sticker replies"),(4,"Suppress role subscription purchase messages"),(5,"Suppress role subscription replies")]{let mut v=flags&(1<<bit)!=0;if ui.checkbox(&mut v,label).changed(){if v{flags|=1<<bit;}else{flags&=!(1<<bit);}}}self.server_edit["system_channel_flags"]=json!(flags);
                    toggle(ui,&mut self.server_edit,"premium_progress_bar_enabled","Show boost progress bar");
                    if ui.button("Change server icon…").clicked(){if let Some(path)=rfd::FileDialog::new().add_filter("Server icon",&["png","jpg","gif","webp"]).pick_file(){match avatar_data(&path){Ok(data)=>self.server_edit["icon"]=json!(data),Err(error)=>self.error=Some(error)}}}
                    if ui.add_enabled(!self.feature_pending.contains("save-server"),primary("Save server changes")).clicked(){let mut body=delta(&self.server.metadata,&self.server_edit);if let Some(obj)=body.as_object_mut(){obj.retain(|k,_|["name","description","preferred_locale","verification_level","default_message_notifications","explicit_content_filter","afk_timeout","afk_channel_id","system_channel_id","system_channel_flags","rules_channel_id","public_updates_channel_id","safety_alerts_channel_id","premium_progress_bar_enabled","icon"].contains(&k.as_str()));}self.mutate("save-server",Method::PATCH,format!("/guilds/{guild}"),Some(body));}
                });if !manage&&!self.preview{ui.weak("Manage Server permission is required to edit these settings.");}self.feature_status(ui,"save-server");ui.separator();ui.collapsing("Server features",|ui|{if let Some(features)=self.server.metadata["features"].as_array(){for feature in features.iter().filter_map(Value::as_str){ui.label(friendly_name(feature));}}});if page=="Community"{ui.weak("Enabling Community and completing Discord's eligibility/onboarding checks still require Discord's own setup flow.");}}
            }
            "Roles"=>self.roles_editor(ui,&actor),
            "Members"=>{
                ui.add(egui::TextEdit::singleline(&mut self.member_search).hint_text("Search loaded members"));ui.weak(format!("{} loaded / {} reported · bounded to 1,000",self.server.members.len(),self.server.metadata["approximate_member_count"].as_u64().or_else(||self.server.metadata["member_count"].as_u64()).unwrap_or(self.server.members.len()as u64)));
                let mut members:Vec<_>=self.server.members.values().filter(|m|m.name().to_lowercase().contains(&self.member_search.to_lowercase())).cloned().collect();members.sort_by_key(|m|m.name().to_lowercase());for member in members{let response=egui::Frame::group(ui.style()).inner_margin(10).show(ui,|ui|{ui.horizontal(|ui|{self.user_avatar(ui,&member.user,member.avatar.as_deref(),34.);ui.vertical(|ui|{ui.strong(member.name());if member.mute{ui.weak("Server muted");}if member.deaf{ui.weak("Server deafened");}ui.horizontal_wrapped(|ui|{for role in self.server.roles.iter().filter(|r|member.roles.contains(&r.id)){let c=role.rgb();ui.colored_label(if c==0{TEXT}else{Color32::from_rgb((c>>16)as u8,(c>>8)as u8,c as u8)},&role.name);}});});});}).response.interact(egui::Sense::click());response.context_menu(|ui|self.user_menu(ui,&member.user));}
                if self.server.has_more&&self.server.members.len()<community::MEMBER_LIMIT&&ui.button("Load next 100 members").clicked(){let after=self.server.cursor.clone().unwrap_or_default();self.request_feature(&format!("members:{guild}"),format!("/guilds/{guild}/members?limit=100&after={after}"));}self.feature_status(ui,&format!("members:{guild}"));
            }
            "Channels"=>self.channels_editor(ui,&actor),
            "Boost Status"=>{ui.label(format!("Boost level {}",self.server.metadata["premium_tier"].as_u64().unwrap_or(0)));ui.label(format!("{} boosts",self.server.metadata["premium_subscription_count"].as_u64().unwrap_or(0)));ui.hyperlink_to("Manage server boosts","https://discord.com/channels/@me");},
            "Notifications"=>{
                let mut data=self.features.get(&key).cloned().unwrap_or_else(||json!({}));toggle(ui,&mut data,"muted","Mute server");choice(ui,&mut data,"message_notifications","Notify for",&[(0,"All messages"),(1,"Only mentions"),(2,"Nothing"),(3,"Use server default")]);toggle(ui,&mut data,"suppress_everyone","Suppress @everyone and @here");toggle(ui,&mut data,"suppress_roles","Suppress all role mentions");toggle(ui,&mut data,"mobile_push","Mobile push notifications");toggle(ui,&mut data,"hide_muted_channels","Hide muted channels");self.features.insert(key.clone(),data.clone());if ui.button("Save notification settings").clicked(){let mut body=data;if let Some(o)=body.as_object_mut(){o.retain(|k,_|["muted","message_notifications","suppress_everyone","suppress_roles","mobile_push","hide_muted_channels"].contains(&k.as_str()));}self.mutate("save-notifications",Method::PATCH,format!("/users/@me/guilds/{guild}/settings"),Some(body));}self.feature_status(ui,"save-notifications");
            }
            "Server Widget"=>{let mut data=self.features.get(&key).cloned().unwrap_or_else(||json!({}));ui.add_enabled_ui(manage,|ui|{toggle(ui,&mut data,"enabled","Enable server widget");channel_choice(ui,&mut data,"channel_id","Invite channel",&self.channels);if ui.button("Save widget").clicked(){self.mutate("server-write",Method::PATCH,format!("/guilds/{guild}/widget"),Some(json!({"enabled":data["enabled"],"channel_id":data["channel_id"]})));}});self.features.insert(key,data);self.feature_status(ui,"server-write");},
            "Vanity URL"=>{let mut data=self.features.get(&key).cloned().unwrap_or_else(||json!({}));ui.add_enabled_ui(manage,|ui|{text(ui,&mut data,"code","Vanity invite code",false);if ui.button("Save vanity URL").clicked(){self.mutate("server-write",Method::PATCH,format!("/guilds/{guild}/vanity-url"),Some(json!({"code":data["code"]})));}});self.features.insert(key,data);ui.weak("Requires Discord's server eligibility for a custom invite link.");self.feature_status(ui,"server-write");},
            "Onboarding"|"Welcome Screen"|"AutoMod"=>{
                if let Some(data)=self.features.get(&key).cloned(){json_cards(ui,&data);ui.collapsing("Configuration details",|ui|{ui.add(egui::Label::new(serde_json::to_string_pretty(&data).unwrap_or_default()).wrap().selectable(true));});ui.weak("Advanced onboarding, AutoMod rule creation and welcome-screen editing are not implemented in this build.");}ui.hyperlink_to("Open server in Discord",format!("https://discord.com/channels/{guild}"));
            }
            _=>self.server_resource_list(ui,&key,&page,&actor),
        }
        ui.add_space(14.);if ui.button("Refresh this section").clicked(){self.load_server_page();}
        });
    }
    fn roles_editor(&mut self,ui:&mut egui::Ui,actor:&str){
        let guild=self.server.id.clone();if self.server.can(actor,28)&&ui.button("Create role").clicked(){self.mutate("create-role",Method::POST,format!("/guilds/{guild}/roles"),Some(json!({"name":"New role","permissions":"0"})));}self.feature_status(ui,"create-role");
        let mut roles=self.server.roles.clone();roles.sort_by_key(|r|std::cmp::Reverse(r.position));for role in roles{let color=role.rgb();let response=ui.add(egui::Button::new(RichText::new(format!("●  {}{}",role.name,if role.managed{"  · integration managed"}else{""})).color(if color==0{TEXT}else{Color32::from_rgb((color>>16)as u8,(color>>8)as u8,color as u8)})).selected(self.role_edit.as_ref().is_some_and(|r|r.id==role.id)));if response.clicked(){self.role_edit=Some(role);}}
        ui.separator();if let Some(mut role)=self.role_edit.clone(){let editable=self.server.can_edit_role(actor,&role);ui.add_enabled_ui(editable||self.preview,|ui|{ui.strong("Role display");ui.text_edit_singleline(&mut role.name);let mut rgb=[(role.rgb()>>16)as u8,(role.rgb()>>8)as u8,role.rgb()as u8];ui.horizontal(|ui|{ui.label("Role color");if ui.color_edit_button_srgb(&mut rgb).changed(){role.color=((rgb[0]as u32)<<16)|((rgb[1]as u32)<<8)|rgb[2]as u32;role.colors=None;}});ui.checkbox(&mut role.hoist,"Display role members separately");ui.checkbox(&mut role.mentionable,"Allow anyone to mention this role");ui.strong("Permissions");let mut bits=role.bits();egui::Grid::new("role-permissions").num_columns(2).spacing([18.,8.]).show(ui,|ui|{for (index,(bit,label))in PERMISSIONS.iter().enumerate(){let flag=1u64<<bit;let mut enabled=bits&flag!=0;let allowed=self.server.permissions(actor)&flag!=0||enabled;ui.add_enabled_ui(allowed,|ui|{if ui.checkbox(&mut enabled,*label).changed(){if enabled{bits|=flag;}else{bits&=!flag;}}});if index%2==1{ui.end_row();}}});role.permissions=bits.to_string();if ui.add_enabled(!self.feature_pending.contains("save-role"),primary("Save role")).clicked(){self.mutate("save-role",Method::PATCH,format!("/guilds/{guild}/roles/{}",role.id),Some(json!({"name":role.name,"permissions":role.permissions,"color":role.color,"hoist":role.hoist,"mentionable":role.mentionable})));}
            if role.id!=guild&&ui.button(RichText::new("Delete role").color(Color32::LIGHT_RED)).clicked(){self.confirm=Some((format!("Permanently delete role {}?",role.name),Command::Request{key:"save-role".into(),method:Method::DELETE,route:format!("/guilds/{guild}/roles/{}",role.id),body:None}));}
        });if !editable&&!self.preview{ui.weak("This role is managed by an integration or is at/above your highest role. Editing is unavailable.");}self.role_edit=Some(role);}self.feature_status(ui,"save-role");
    }
    fn channels_editor(&mut self,ui:&mut egui::Ui,actor:&str){
        let manage=self.server.can(actor,4);let guild=self.server.id.clone();let mut selected=None;
        for channel in self.channels.clone(){if ui.selectable_label(self.features.get("channel-edit").is_some_and(|v|v["id"].as_str()==Some(&channel.id)),format!("{} {}",if channel.kind==2{"Voice"}else if channel.kind==4{"Category"}else{"#"},channel.label())).clicked(){selected=Some(channel);}}
        if let Some(channel)=selected{self.features.insert("channel-edit".into(),json!({"id":channel.id,"name":channel.name,"topic":channel.topic,"type":channel.kind,"rate_limit_per_user":channel.rate_limit_per_user,"bitrate":channel.bitrate.unwrap_or(64000),"user_limit":channel.user_limit.unwrap_or(0),"nsfw":channel.nsfw}));}
        if let Some(mut edit)=self.features.get("channel-edit").cloned(){ui.separator();ui.add_enabled_ui(manage||self.preview,|ui|{text(ui,&mut edit,"name","Channel name",false);text(ui,&mut edit,"topic","Topic",true);toggle(ui,&mut edit,"nsfw","Age-restricted channel");if edit["type"].as_u64()==Some(2){number(ui,&mut edit,"bitrate","Bitrate",8000..=384000);number(ui,&mut edit,"user_limit","User limit (0 = unlimited)",0..=99);}else{number(ui,&mut edit,"rate_limit_per_user","Slowmode seconds",0..=21600);}if ui.button("Save channel").clicked(){if let Some(id)=edit["id"].as_str().map(str::to_owned){let mut body=edit.clone();body.as_object_mut().unwrap().remove("id");body.as_object_mut().unwrap().remove("type");self.mutate("save-channel",Method::PATCH,format!("/channels/{id}"),Some(body));}}});self.features.insert("channel-edit".into(),edit);}
        if manage {ui.separator();let mut create=self.features.get("new-channel").cloned().unwrap_or_else(||json!({"name":"new-channel","type":0}));text(ui,&mut create,"name","New channel name",false);choice(ui,&mut create,"type","Channel type",&[(0,"Text"),(2,"Voice"),(4,"Category")]);if ui.button("Create channel").clicked(){self.mutate("create-channel",Method::POST,format!("/guilds/{guild}/channels"),Some(create.clone()));}self.features.insert("new-channel".into(),create);}self.feature_status(ui,"save-channel");self.feature_status(ui,"create-channel");
    }
    fn server_resource_list(&mut self,ui:&mut egui::Ui,key:&str,page:&str,actor:&str){
        let guild=self.server.id.clone();let data=self.features.get(key).cloned().unwrap_or(Value::Null);let items=data.as_array().or_else(||data["items"].as_array()).or_else(||data["audit_log_entries"].as_array());
        if let Some(items)=items{if items.is_empty(){ui.weak("No entries.");}for item in items.iter().take(200){egui::Frame::group(ui.style()).inner_margin(12).show(ui,|ui|{let name=item["name"].as_str().or_else(||item["user"]["global_name"].as_str()).or_else(||item["user"]["username"].as_str()).or_else(||item["code"].as_str()).unwrap_or("Entry");ui.strong(name);if let Some(reason)=item["reason"].as_str(){ui.label(reason);}if let Some(action)=item["action_type"].as_u64(){ui.weak(audit_action(action));if let Some(user)=item["user_id"].as_str().and_then(|id|self.server.members.get(id)){ui.label(format!("By {}",user.name()));}if self.prefs.developer{ui.collapsing("Technical details",|ui|{ui.label(format!("Action {action}"));ui.label(format!("Target: {}",item["target_id"].as_str().unwrap_or("Unknown")));});}}
            if page=="Emoji"{if let(Some(id),Some(animated))=(item["id"].as_str(),item["animated"].as_bool()){if let Some(url)=crate::media_picker::emoji_url(id,animated){crate::message_media::picture(ui,&mut self.images,&url,Some(64),Some(64),false);}}}
            if page=="Invites"{if let Some(code)=item["code"].as_str(){ui.hyperlink_to("Copy / open invitation",format!("https://discord.gg/{code}"));}}
            if page=="Bans"&&self.server.can(actor,2){if let Some(id)=item["user"]["id"].as_str(){if ui.button("Revoke ban").clicked(){self.confirm=Some((format!("Unban {name}?"),Command::Request{key:"server-write".into(),method:Method::DELETE,route:format!("/guilds/{guild}/bans/{id}"),body:None}));}}}
            if matches!(page,"Emoji"|"Stickers")&&self.server.can(actor,30){if let Some(id)=item["id"].as_str(){if ui.button("Delete").clicked(){let resource=if page=="Emoji"{"emojis"}else{"stickers"};self.confirm=Some((format!("Delete {name} from this server?"),Command::Request{key:"server-write".into(),method:Method::DELETE,route:format!("/guilds/{guild}/{resource}/{id}"),body:None}));}}}
        });ui.add_space(8.);}}else if !data.is_null(){json_cards(ui,&data);}else if !self.feature_pending.contains(key){ui.weak("Choose Refresh this section to load data. Discord may restrict this section based on your permissions.");}
        if page=="Emoji"&&self.server.can(actor,43){ui.separator();let mut upload=self.features.get("new-emoji").cloned().unwrap_or_else(||json!({"name":"new_emoji"}));text(ui,&mut upload,"name","New emoji name",false);if ui.button("Choose image and upload emoji…").clicked(){if let Some(path)=rfd::FileDialog::new().add_filter("Emoji image",&["png","gif","webp","jpg"]).pick_file(){match avatar_data(&path){Ok(image)=>{upload["image"]=json!(image);self.mutate("server-write",Method::POST,format!("/guilds/{guild}/emojis"),Some(upload.clone()));},Err(error)=>self.error=Some(error)}}}upload.as_object_mut().unwrap().remove("image");self.features.insert("new-emoji".into(),upload);}
        self.feature_status(ui,"server-write");
    }
}
fn channel_choice(ui:&mut egui::Ui,value:&mut Value,key:&str,label:&str,channels:&[Channel]){let mut selected=value[key].as_str().map(str::to_owned);ui.label(label);egui::ComboBox::from_id_salt(key).selected_text(selected.as_ref().and_then(|id|channels.iter().find(|c|&c.id==id)).map(Channel::label).unwrap_or("None".into())).show_ui(ui,|ui|{ui.selectable_value(&mut selected,None,"None");for c in channels{ui.selectable_value(&mut selected,Some(c.id.clone()),c.label());}});value[key]=selected.map(Value::String).unwrap_or(Value::Null);}
const PERMISSIONS:&[(u8,&str)]=&[(0,"create instant invite"),(1,"kick members"),(2,"ban members"),(3,"administrator"),(4,"manage channels"),(5,"manage guild"),(6,"add reactions"),(7,"view audit log"),(8,"priority speaker"),(9,"stream"),(10,"view channel"),(11,"send messages"),(12,"send tts messages"),(13,"manage messages"),(14,"embed links"),(15,"attach files"),(16,"read message history"),(17,"mention everyone"),(18,"use external emojis"),(19,"view guild insights"),(20,"connect"),(21,"speak"),(22,"mute members"),(23,"deafen members"),(24,"move members"),(25,"use vad"),(26,"change nickname"),(27,"manage nicknames"),(28,"manage roles"),(29,"manage webhooks"),(30,"manage guild expressions"),(31,"use application commands"),(32,"request to speak"),(33,"manage events"),(34,"manage threads"),(35,"create public threads"),(36,"create private threads"),(37,"use external stickers"),(38,"send messages in threads"),(39,"use embedded activities"),(40,"moderate members"),(41,"view creator monetization analytics"),(42,"use soundboard"),(43,"create guild expressions"),(44,"create events"),(45,"use external sounds"),(46,"send voice messages"),(48,"set voice channel status"),(49,"send polls"),(50,"use external apps"),(51,"pin messages"),(52,"bypass slowmode")];
